import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
	// const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
	return (
		<>
			<Head>
				<title>Coupon Buddies</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
				<Content />
			</main>
		</>
	);
};

export default Home;

const Content = () => {
	const { data, status } = useSession();
	if (status === "authenticated") {
		return (
			<div className="flex flex-col">
				<p>Hey {data?.user?.name}</p>
				<Link href={"/chat"}>
					<a href="#" className="text-blue-800 hover:text-blue-600">
						Profile Page
					</a>
				</Link>
				<button
					type={"button"}
					onClick={() => signOut()}
					className="text-blue-800 hover:text-blue-600"
				>
					Logout
				</button>
			</div>
		);
	}
	if (status === "loading") {
		return <p>Loading...</p>;
	}
	return (
		<>
			<button
				type={"button"}
				onClick={() => signIn("discord")}
				className="text-blue-800 hover:text-blue-600"
			>
				Login Discord
			</button>
		</>
	);
};
