import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FriendsLayout } from "../components/layouts/FriendsLayout";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Coupon Buddies</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container relative mx-auto flex h-screen border-2 border-black">
				<FriendsLayout>
					<h1 className="mb-20 text-3xl">Profile Page</h1>

					<Link href={"/"}>
						<a href="#" className="mt-10 text-blue-800 hover:text-blue-600">
							Return to Home
						</a>
					</Link>
				</FriendsLayout>
			</main>
		</>
	);
};

export default Home;
