import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Coupon Buddies</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto mt-36 flex min-h-screen flex-col items-center">
        <button>some button</button>
        <Link href={"/"}>
          <a href="#" className="mt-10 text-blue-800 hover:text-blue-600">
            Return to Home
          </a>
        </Link>
      </main>
    </>
  );
};

export default Home;
